/*
Assignment: STAT_6430_2 Project 1
Author: Jason Lewris
Computing ID: JL4PT

The aim of this project is to create a dataset containing information on rates of 
municipal, agricultural, and industrial water use by country. 

AVAILABLE DATA

Raw data relevant to this task can be found at the following locations:

	-aquastat.csv contains the most recent available data on total volumes of 
	municipal, industrial, and agricultural water use by country. This data is 
	generated by a query to the Food and Agriculture Organizations AQUASTAT 
	database at www.fao.org/nr/water/aquastat/data.

	-Data_Extract_From_World_Development_Indicators_Data.txt contains 2014 data on 
	population and GDP, as well as a number of development indices. This data was generated
	by a query to the World Bank's World DataBank at databank.worldbank.org/data/.

Take a look at each file in text editor to see how they are formatted. Make sure to look 
at both the top and bottom of the files. 

STEP-BY-STEP

1) Import and prepare water data.

*/

FILENAME aquafile 'C:\Users\Jason\Desktop\MyLife\UVA\STAT_6430\SAS_Class\Projects\Project_1\aquastat.csv';
FILENAME worldfile 'C:\Users\Jason\Desktop\MyLife\UVA\STAT_6430\SAS_Class\Projects\Project_1\Data_Extract_From_World_Development_Indicators_Data.txt';

/*
1.A) Import the aquastat.csv data into SAS. If you use the import wizard make sure to 
include the generated PROC IMPORT code in your program. 

1.B) Only keep variables corresponding to country name, global region, agricultural withdrawl,
industrial withdrawl, and total withdrawl. After this step your dataset should 
have six variables. 

1.C) Make sure each variable has an appropriate type, format, name, and label.

 **Please note the following variables
	  Variable Name			  Variable Type    Variable Label
	1) country_name           Type: Character  (Name of the country)
	2) global_region	      Type: Character  (Region of the world country is located)
	3) agr_withdrawl	      Type: Numeric    (Agricultural withdrawl 10^9 m3/year)
	4) ind_withdrawl		  Type: Numeric    (Industrial withdrawl 10^9 m3/year)
	5) muni_withdrawl		  Type: Numeric    (Municipal water withdrawl 10^9 m3/year)
	6) total_withdrawl	  	  Type: Numeric    (Total water withdrawl 10^9 m3/year)

  **Please also note that the first observation read in was line 2 due to wanting to remove the headers within the csv file
    Additionally, the last observation read in was 201 due to the remainder of the csv file containing metadata
*/


DATA aquadata(DROP=Drop1 Drop2 Drop3 Drop4 Drop5 Drop6 Drop7 Drop8 Drop9 Drop10 Drop11 Drop12 Drop13 Drop14 Drop15 Drop16);
	INFILE aquafile DSD DLM=',' FIRSTOBS=2 OBS=201;
	INPUT Drop1 $ :15. 
		  Country_Name $:30. 
		  Global_Region $:30. 
          Drop2 $:5. 
          Agr_Withdrawl :15. 
          Drop3 $:5.
		  Drop4 $:8.
		  Drop5 $:6.
		  Ind_Withdrawl :25.
		  Drop6 $:3.
		  Drop7 $:5.
		  Drop8 $:6.
		  Muni_Withdrawl :15.
		  Drop9 $:10.
		  Drop10 $:10.
		  Drop11 $:5.
		  Total_Withdrawl :20.
		  Drop12 $:5.
		  Drop13 $:10.
		  Drop14 $:6.
		  Drop15 :10.
		  Drop16 $:3.;
	LABEL Country_Name = 'Country Name'
	      Global_Region = 'Region of the world in which the Country exists'
		  Agr_Withdrawl = 'Agricultural withdrawl 10^9 m3/year'
		  Ind_Withrdawl = 'Industrial withrawl 10^9 m3/year'
		  Muni_Withdrawl = 'Municipal water withdrawl 10^9 m3/year'
		  Total_Withdrawl = 'Total water withdrawl 10^9 m3/year'
RUN;

PROC PRINT DATA=aquadata;
	TITLE 'testing aquadata';
RUN;

